apiVersion: v1
data:
  authentication_tpl.csv: aWQ7ZW1haWw7cm9sZTtoYXNoZWRfcGFzc3dvcmQ7ZGlzYWJsZWQKMDthbGljZUBnbWFpbC5jb207dXNlcjskMmIkMTIkeTBYYTBTb3pYUFVYYjQuNXkyeS8vTzAxa0R4T1gwZXh5NGVSOUFiNVI1YVFEb0NlTEtocHk7RmFsc2UKMTtib2JAZ21haWwuY29tO3VzZXI7JDJiJDEyJGc3cTN1dkx1RlZ2Lk9uYm9oMko2R09EM1pUUFRndFhXTUdwQmM1MWgzRXgxZ0ZFekZubFU2O0ZhbHNlCjI7Y2xlbWVudGluZUBnbWFpbC5jb207dXNlcjskMmIkMTIkeUZFYS5GWmlWVnRjZnF2QjU5VWxzdXdjR09FUnRTZk45dHJlVDcwdnFRcUlLOHFJMVdkZVM7RmFsc2UKMzthZG1pbjthZG1pbjskMmIkMTIkTnBRcW1CbEFHZzRVcmJ5Z3lHdG5NT2ouZjRUbEY2VUpGQVgwTEJiNXJmOGRESi9nZTBjNGU7RmFsc2UK
kind: Secret
metadata:
  name: auth
