name: Python application test with Github Actions

on: [push]

env:
  REGISTRY: docker.io
  IMAGE_NAME: strivly/covid
  PROJECT_ID: strivly
  GKE_CLUSTER: gke-covid
  GKE_ZONE: europe-west9

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "Datascientest_FastAPI"
      ALGORITHM: "HS256"
      ACESS_TOKEN_EXPIRE_MINUTE : 120
      API_PORT : 8000
      DB_AUTH_STORAGE_PATH: "./api"
      API_USER_EMAIL: "admin"
      API_USER_PASSWORD: "4dm1N"
      STORAGE_PATH: "./storage"
      PROD_MODEL_NAME: "mlops_cnn_vit_model_weights"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests with pytest
      run: |
        pytest
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: dsmlopscovid
        password: qsdfghjklm
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: dsmlopscovid/project
      
    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
