name: Python application test with Github Actions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MY_ENV_VARIABLE: "SomeValue"
      ANOTHER_ENV_VARIABLE: "AnotherValue"
      SECRET_KEY: "Datascientest_FastAPI"
      ALGORITHM: "HS256"
      ACESS_TOKEN_EXPIRE_MINUTE : 120
      API_PORT : 8000
      DB_AUTH_STORAGE_PATH: "https://github.com/luc-perso/DS_MLOps/tree/dev_yb/api"
      API_USER_EMAIL: "admin"
      API_USER_PASSWORD: "4dm1N"
      STORAGE_PATH: "https://github.com/luc-perso/DS_MLOps/tree/dev_yb/storage"
      PROD_MODEL_NAME: "mlops_cnn_vit_model_weights"

    steps:
    - uses: actions/checkout@v2
    - name: "repertoire courant"
      run: pwd
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests with pytest
      run: |
        pytest
