name: Python application test with Github Actions

on: [push, pull_request]

env:
  REGISTRY: docker.io
  IMAGE_NAME: strivly/covid
  PROJECT_ID: strivly
  GKE_CLUSTER: gke-covid
  GKE_ZONE: europe-west9

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MY_ENV_VARIABLE: "SomeValue"
      ANOTHER_ENV_VARIABLE: "AnotherValue"
      SECRET_KEY: "Datascientest_FastAPI"
      ALGORITHM: "HS256"
      ACESS_TOKEN_EXPIRE_MINUTE : 120
      API_PORT : 8000
      DB_AUTH_STORAGE_PATH: "./api"
      API_USER_EMAIL: "admin"
      API_USER_PASSWORD: "4dm1N"
      STORAGE_PATH: "./storage"
      PROD_MODEL_NAME: "mlops_cnn_vit_model_weights"

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests with pytest
      run: |
        pytest
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: strivly
        password: r7P1sV@6i0j1
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - uses: google-github-actions/setup-gcloud@1bee7de035d65ec5da40a31f8589e240eba8fde5
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ env.GKE_PROJECT }}
    - name: Init gcloud
      shell: bash
      run: |-
        gcloud --quiet auth configure-docker
        gcloud config set project strivly
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
    - name: Deploy to gke
      shell: bash
      run: |-
        curl -LO https://dl.k8s.io/release/v1.25.8/bin/linux/amd64/kubectl
        chmod +x kubectl
        ./kubectl apply -f k8s
